"""
SEO Page Publisher - Renders SEO content as static HTML pages for Google indexing.
"""

import os
import logging
from pathlib import Path
from typing import Dict, Optional
from datetime import datetime
from jinja2 import Template
import httpx
from apps.api.config import settings

logger = logging.getLogger(__name__)


class SeoPagePublisher:
    """
    Publisher that renders SEO content as static HTML pages for Google indexing.
    Serves pages via nginx at configured path.
    """
    
    def __init__(self, agent_name: Optional[str] = None):
        self._agent_name = agent_name
        self._output_dir = Path(getattr(settings, "SEO_PAGES_OUTPUT_DIR", "/var/www/html/seo"))
        self._base_url = getattr(settings, "SEO_PAGES_BASE_URL", "https://example.com/seo")
        self._initialized = False
        
    def _ensure_initialized(self):
        """Ensure output directory exists."""
        if self._initialized:
            return
        
        self._output_dir.mkdir(parents=True, exist_ok=True)
        self._initialized = True
        
    def _generate_html(self, content: Dict) -> str:
        """Generate HTML page from SEO content."""
        seo_metadata = content.get("variants", {})
        
        html_template = Template("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ meta_title }}</title>
    <meta name="description" content="{{ meta_description }}">
    <meta name="keywords" content="{{ keywords|join(', ') }}">
    <link rel="canonical" href="{{ canonical_url }}">
    
    <!-- JSON-LD Structured Data -->
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "{{ h1 }}",
        "description": "{{ meta_description }}",
        "datePublished": "{{ publication_date }}",
        "author": {
            "@type": "Organization",
            "name": "AiFinPay"
        }
    }
    </script>
</head>
<body>
    <header>
        <h1>{{ h1 }}</h1>
    </header>
    <main>
        <article>
            {{ body|safe }}
        </article>
    </main>
    <footer>
        <p>Generated by AiFinPay Autonomous Marketing OS</p>
    </footer>
</body>
</html>
""")
        
        canonical_url = f"{self._base_url}/{content['id']}.html"
        
        return html_template.render(
            meta_title=seo_metadata.get("seo_title_tag", content.get("title", "")),
            meta_description=seo_metadata.get("meta_description", ""),
            keywords=seo_metadata.get("keywords", []),
            h1=seo_metadata.get("h1", content.get("title", "")),
            canonical_url=canonical_url,
            publication_date=content.get("created_at", datetime.utcnow().isoformat()),
            body=content.get("body", "")
        )
    
    async def publish_post(self, title: str, body: str, **kwargs) -> Dict:
        """
        Render and save SEO content as static HTML page.
        
        Returns normalized dict with keys:
        - success: bool
        - dry_run: bool
        - post_id: Optional[str]
        - post_url: Optional[str]
        """
        self._ensure_initialized()
        
        content_id = kwargs.get("content_id")
        variants = kwargs.get("variants", {})
        
        if not content_id:
            return {
                "success": False,
                "dry_run": True,
                "post_id": None,
                "post_url": None,
                "error": "content_id required for SEO page publishing"
            }
        
        try:
            # Build content dict for template
            content = {
                "id": content_id,
                "title": title,
                "body": body,
                "variants": variants,
                "created_at": datetime.utcnow().isoformat()
            }
            
            # Generate HTML
            html = self._generate_html(content)
            
            # Save to file
            filename = f"{content_id}.html"
            filepath = self._output_dir / filename
            
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(html)
            
            # Generate canonical URL
            post_url = f"{self._base_url}/{filename}"
            
            logger.info(f"SEO page published: {filepath} -> {post_url}")
            
            # Regenerate sitemap and robots.txt after each page
            self._update_sitemap_and_robots()
            
            # Submit to IndexNow if key is configured
            indexing_status = "pending"
            if getattr(settings, "SEO_INDEXNOW_KEY", None):
                indexing_status = await self._submit_to_indexnow(post_url)
            
            # Return metadata for updating content item
            return {
                "success": True,
                "dry_run": False,
                "post_id": content_id,
                "post_url": post_url,
                "canonical_url": post_url,
                "target_keyword": variants.get("keywords", [""])[0] if variants.get("keywords") else None,
                "meta_title": variants.get("seo_title_tag", title),
                "meta_description": variants.get("meta_description", ""),
                "indexing_status": indexing_status
            }
            
        except Exception as e:
            logger.error(f"Failed to publish SEO page: {e}")
            return {
                "success": False,
                "dry_run": True,
                "post_id": None,
                "post_url": None,
                "error": str(e)
            }
    
    async def close(self):
        """No resources to clean up."""
        pass
    
    def _update_sitemap_and_robots(self):
        """Regenerate and write sitemap.xml and robots.txt to output directory."""
        try:
            sitemap = self._generate_sitemap_content()
            sitemap_path = self._output_dir / "sitemap.xml"
            with open(sitemap_path, "w", encoding="utf-8") as f:
                f.write(sitemap)
            logger.info(f"Sitemap updated: {sitemap_path}")
            
            robots = self._generate_robots_content()
            robots_path = self._output_dir / "robots.txt"
            with open(robots_path, "w", encoding="utf-8") as f:
                f.write(robots)
            logger.info(f"Robots.txt updated: {robots_path}")
        except Exception as e:
            logger.error(f"Failed to update sitemap/robots: {e}")
    
    async def _submit_to_indexnow(self, url: str) -> str:
        """Submit URL to IndexNow API for faster indexing."""
        indexnow_key = getattr(settings, "SEO_INDEXNOW_KEY", None)
        if not indexnow_key:
            return "pending"
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    "https://www.indexnow.org/indexnow",
                    json={
                        "host": self._base_url.replace("https://", "").replace("http://", "").split("/")[0],
                        "key": indexnow_key,
                        "urlList": [url]
                    },
                    headers={"Content-Type": "application/json"}
                )
                if response.status_code == 200:
                    logger.info(f"IndexNow submission successful for {url}")
                    return "submitted"
                else:
                    logger.warning(f"IndexNow submission failed: {response.status_code}")
                    return "pending"
        except Exception as e:
            logger.error(f"IndexNow submission error: {e}")
            return "pending"
    
    def _generate_sitemap_content(self) -> str:
        """Generate sitemap.xml content for all published SEO pages."""
        if not self._output_dir.exists():
            return ""
        
        pages = list(self._output_dir.glob("*.html"))
        
        sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n'
        sitemap += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        
        for page in pages:
            url = f"{self._base_url}/{page.name}"
            sitemap += f'  <url>\n    <loc>{url}</loc>\n  </url>\n'
        
        sitemap += '</urlset>'
        
        return sitemap
    
    def _generate_robots_content(self) -> str:
        """Generate robots.txt content to allow indexing of SEO pages."""
        return f"""User-agent: *
Allow: /blog/
Disallow: /api/
Disallow: /admin/

Sitemap: {self._base_url}/sitemap.xml
"""
    
    def generate_sitemap(self) -> str:
        """Generate sitemap.xml for all published SEO pages and write to file."""
        if not self._output_dir.exists():
            return ""
        
        sitemap = self._generate_sitemap_content()
        sitemap_path = self._output_dir / "sitemap.xml"
        with open(sitemap_path, "w", encoding="utf-8") as f:
            f.write(sitemap)
        
        return sitemap
    
    def generate_robots_txt(self) -> str:
        """Generate robots.txt to allow indexing of SEO pages and write to file."""
        robots = self._generate_robots_content()
        robots_path = self._output_dir / "robots.txt"
        with open(robots_path, "w", encoding="utf-8") as f:
            f.write(robots)
        
        return robots
